### ISSUE TITLE
你好，运行代码遇到crash问题

### ISSUE THREAD

**Issue by BetterZhang** [wisdomtl/FrameSurfaceView#4]
手机系统信息：MIUI 12， Android 10

--------- beginning of crash
2020-11-05 10:31:09.593 30009-30051/taylor.com.framesurfaceview E/AndroidRuntime: FATAL EXCEPTION: DecodingThread
    Process: taylor.com.framesurfaceview, PID: 30009
    android.content.res.Resources$NotFoundException: File res/raw/frame18.png from drawable resource ID #0x7f0e000a
        at android.content.res.ResourcesImpl.openRawResource(ResourcesImpl.java:362)
        at android.content.res.MiuiResourcesImpl.openRawResource(MiuiResourcesImpl.java:170)
        at android.content.res.Resources.openRawResource(Resources.java:1317)
        at android.content.res.Resources.openRawResource(Resources.java:1261)
        at taylor.lib.framesurfaceview.FrameSurfaceView.decodeBitmap(FrameSurfaceView.java:285)
        at taylor.lib.framesurfaceview.FrameSurfaceView.putDecodedBitmap(FrameSurfaceView.java:299)
        at taylor.lib.framesurfaceview.FrameSurfaceView.putDecodedBitmapByReuse(FrameSurfaceView.java:295)
        at taylor.lib.framesurfaceview.FrameSurfaceView.access$000(FrameSurfaceView.java:22)
        at taylor.lib.framesurfaceview.FrameSurfaceView$DecodeRunnable.run(FrameSurfaceView.java:361)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:224)
        at android.os.HandlerThread.run(HandlerThread.java:67)
     Caused by: java.io.FileNotFoundException: res/raw/frame18.png
        at android.content.res.AssetManager.nativeOpenNonAsset(Native Method)
        at android.content.res.AssetManager.openNonAsset(AssetManager.java:973)
        at android.content.res.ResourcesImpl.openRawResource(ResourcesImpl.java:356)
        at android.content.res.MiuiResourcesImpl.openRawResource(MiuiResourcesImpl.java:170) 
        at android.content.res.Resources.openRawResource(Resources.java:1317) 
        at android.content.res.Resources.openRawResource(Resources.java:1261) 
        at taylor.lib.framesurfaceview.FrameSurfaceView.decodeBitmap(FrameSurfaceView.java:285) 
        at taylor.lib.framesurfaceview.FrameSurfaceView.putDecodedBitmap(FrameSurfaceView.java:299) 
        at taylor.lib.framesurfaceview.FrameSurfaceView.putDecodedBitmapByReuse(FrameSurfaceView.java:295) 
        at taylor.lib.framesurfaceview.FrameSurfaceView.access$000(FrameSurfaceView.java:22) 
        at taylor.lib.framesurfaceview.FrameSurfaceView$DecodeRunnable.run(FrameSurfaceView.java:361) 
        at android.os.Handler.handleCallback(Handler.java:883) 
        at android.os.Handler.dispatchMessage(Handler.java:100) 
        at android.os.Looper.loop(Looper.java:224) 
        at android.os.HandlerThread.run(HandlerThread.java:67)

**Comment by BetterZhang** [comment]
进入App，点击start frame animation by FrameSurfaceView，动画不停的播放一段时间后出现这个crash的问题。
